---

- name: Create k3s install configuration directory
  file:
    path: "{{ k3s_config_path }}"
    owner: "root"
    group: "root"
    mode: "0555"
    state: "directory"

- name: Put in place k3s install configuration file
  template:
    src: "k3s_config.j2"
    dest: "{{ k3s_config_path }}/config.yaml"
    owner: "root"
    group: "root"
    mode: "0444"
