---

- name: Download k3s installation script 
  get_url:
    url: "{{ k3s_install_script_url }}"
    dest: "{{ k3s_install_script }}"
    owner: "root"
    group: "root"
    mode: "0750"

- name: Install k3s instance 
  shell: >
    INSTALL_K3S_VERSION="{{ k3s_version }}" {{ k3s_install_script }}

- name: Remove k3s installation script 
  file:
    path: "{{ k3s_install_script }}"
    state: absent