---

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: Install iptables-services
  package:
    name: iptables-services
    state: present
  notify: Enable firewall

- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  notify: Save firewall rules

- name: Allow ICMP
  iptables:
    chain: INPUT
    protocol: ICMP
    jump: ACCEPT

- name: Allow Loopback
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  notify: Save firewall rules

- name: Allow ssh
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: ssh
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept new SSH connections
  notify: Save firewall rules

# port list at https://rancher.com/docs/k3s/latest/en/installation/installation-requirements/
- name: Allow k3s
  iptables:
    chain: INPUT
    protocol: '{{ item.0.protocol }}'
    destination_port: '{{ item.0.port }}'
    source: '{{ item.1 }}'
    ctstate: NEW
    syn: match
    jump: ACCEPT
    comment: Accept k3s
  when: k3s_sources is defined
  loop: '{{ k3s_ports | product(k3s_sources) | list }}'
  notify: Save firewall rules

- name: Default deny incoming connections
  iptables:
    chain: INPUT
    policy: DROP
  notify: Save firewall rules
