---

- import_tasks: k3s_iptables.yml
  tags:
    - k3s-iptables

- import_tasks: k3s_setup.yml
  tags:
    - k3s-setup

- import_tasks: k3s_install.yml
  tags:
    - k3s-install

- import_tasks: k3s_traefik.yml
  tags:
    - k3s-traefik
