---

- name: Enable firewall
  service:
    name: iptables
    enabled: true
    state: started

- name: Save firewall rules
  command:
    cmd: service iptables save
    warn: false  # noqa command-instead-of-module
  changed_when: '"Saving firewall rules" in firewall_save.stdout'
  register: firewall_save

- name: Remove k3s installer
  file:
    path: '{{ k3s_installer.path }}'
    state: absent
  check_mode: false

- name: Start k3s
  service:
    name: k3s
    enabled: true
    state: started
